# Generated by Django 4.1.13 on 2024-05-08 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airlineCode', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icaoCode', models.CharField(max_length=50)),
                ('iataCode', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('isInsideCity', models.BooleanField()),
                ('location', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default=' ', max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('income', models.DecimalField(decimal_places=3, max_digits=100)),
                ('dateOfBirth', models.DateField()),
                ('photo', models.ImageField(upload_to='')),
                ('middleName', models.CharField(default=' ', max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('age', models.SmallIntegerField()),
                ('favoriteFeature', models.TextField()),
                ('features', models.CharField(choices=[('feature1', 'Feature 1'), ('feature2', 'Feature 2'), ('feature3', 'Feature 3'), ('feature4', 'Feature 4')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripId', models.SmallIntegerField()),
                ('shareId', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('budget', models.BigIntegerField()),
                ('description', models.TextField()),
                ('startsAt', models.DateField()),
                ('endsAt', models.DateField()),
                ('cost', models.FloatField()),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airdetail.person')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='documents/')),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airdetail.person')),
            ],
        ),
    ]
