# Generated by Django 4.1.13 on 2024-05-23 07:12

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Airdetail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=100)),
                ('country', models.CharField(default=True, max_length=100)),
                ('region', models.CharField(default=True, max_length=100)),
                ('address', models.CharField(default=True, max_length=100)),
                ('city', models.CharField(default=True, max_length=100)),
                ('buildinginfo', models.CharField(default=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='trip',
            name='endTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='startTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='addressInfo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='addressInfo', to='Airdetail.address'),
        ),
        migrations.AddField(
            model_name='person',
            name='homeAddress',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='homeAddress', to='Airdetail.address'),
        ),
    ]
