# Generated by Django 4.1.13 on 2024-06-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airdetail', '0002_address_person_emails_trip_endtime_trip_starttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
